### ISSUE TITLE
pkgdown

### ISSUE THREAD

**Issue by maelle** [ropensci/europepmc#24]
Now that there are 2 vignettes it might be great to build a website with `pkgdown`?

**Comment by njahn82** [comment]
Guess, this issue refers to pkgdown and not to blogdown. However, just started to play around with Hugo and the blogdown package and I like it very much!

**Comment by maelle** [comment]
yup I was wrong! any -down package is good these days 😁

**Comment by maelle** [comment]
The website looks great 😍

**Comment by njahn82** [comment]
Up and linked (#21), looks great!

**Comment by maelle** [comment]
The only "issue" is the "#" of the title of the evergreen review graphs vignette being recognized as title, otherwise it's just so pretty and handy!

**Comment by njahn82** [comment]
Will fix it and find a better title, many thanks for your great help, learned a lot!

**Comment by maelle** [comment]
you're welcome, that's a payment for what I learnt reading the vignette 😜

**Comment by njahn82** [comment]
Will close this ticket because pgkdown is now used for documentation.
