### ISSUE TITLE
GitHub topics

### ISSUE THREAD

**Issue by maelle** [ropensci/europepmc#30]
:wave: @njahn82!

I added a few GitHub repo topics 

![image](https://user-images.githubusercontent.com/8360597/40723752-db22de6a-641f-11e8-9257-ec610d26549b.png)

Please feel free to add/delete some (I'd recommend keeping "r" and "rstats" though)!

**Comment by njahn82** [comment]
Great, @maelle super helpful, thanks!

**Comment by maelle** [comment]
Cool!
