### ISSUE TITLE
set default batch_size to 1000 and limit to 25?

### ISSUE THREAD

**Issue by cstubben** [ropensci/europepmc#5]
Also, I think setting both the batch_size and limit is confusing in epmc_search.   I can't think of a good reason to not get the maximum pageSize of 1000 ( instead of paging through 10 rest queries of 100 results each).    In fact, I would drop batch_size as an option and just have a limit =25 for a default.

**Comment by njahn82** [comment]
Thanks, the default limit is 25. Batch_size is by default 1000 and is dropped as function parameter. I will implement this behavior also for the other functions that need to loop over result pages.

**Comment by cstubben** [comment]
Works great, thanks!
